version: "3.8"

services:
  front:
    build: 
      context: ./front
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      -3000:5173
    volumes:
      - ./front/:/front
    depends_on:
      - backend
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 80:80
    volumes:
       - ./backend/:/app